# Generated by Django 5.1.3 on 2025-03-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandou", "0003_alter_movie_brief_introduction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="type",
        ),
        migrations.DeleteModel(
            name="Type",
        ),
        migrations.AddField(
            model_name="movie",
            name="type",
            field=models.CharField(default="待定", max_length=32, verbose_name="电影类别"),
            preserve_default=False,
        ),
    ]
