# Generated by Django 5.1.3 on 2025-03-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandou", "0006_alter_user_managers_remove_user_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
        ),
    ]
