# Generated by Django 5.1.3 on 2025-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandou", "0007_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.FloatField(default=5, verbose_name="评分"),
        ),
    ]
