# Generated by Django 5.1.3 on 2025-04-26 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandou", "0009_alter_rating_rating_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="bandou.comments",
                verbose_name="父评论",
            ),
        ),
    ]
