# Generated by Django 5.1.3 on 2025-02-22 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(max_length=32, unique=True, verbose_name="电影类别名"),
                ),
            ],
            options={
                "verbose_name": "电影类别信息",
                "verbose_name_plural": "电影类别信息",
                "db_table": "type",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=32, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=16, verbose_name="密码")),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "用户信息",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="片名")),
                (
                    "brief_introduction",
                    models.CharField(max_length=255, verbose_name="简介"),
                ),
                ("cover_url", models.CharField(max_length=255, verbose_name="封面url")),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="评分"),
                ),
                ("release_time", models.DateField(verbose_name="上映时间")),
                ("director", models.CharField(max_length=32, verbose_name="导演")),
                ("starring", models.CharField(max_length=128, verbose_name="主演")),
                (
                    "type",
                    models.ManyToManyField(
                        related_name="movies", to="bandou.type", verbose_name="电影类别"
                    ),
                ),
            ],
            options={
                "verbose_name": "电影信息",
                "verbose_name_plural": "电影信息",
                "db_table": "movie",
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="评论")),
                ("comment_time", models.DateTimeField(verbose_name="评论时间")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bandou.movie",
                        verbose_name="电影",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bandou.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论信息",
                "verbose_name_plural": "评论信息",
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=5, verbose_name="评分")),
                ("rating_time", models.DateTimeField(verbose_name="评分时间")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bandou.movie",
                        verbose_name="电影",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bandou.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评分信息",
                "verbose_name_plural": "评分信息",
                "db_table": "rating",
                "unique_together": {("user", "movie")},
            },
        ),
    ]
