# Generated by Django 5.1.3 on 2025-03-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandou", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="starring",
            field=models.CharField(max_length=255, verbose_name="主演"),
        ),
    ]
