# Generated by Django 5.1.3 on 2025-03-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandou", "0002_alter_movie_starring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="brief_introduction",
            field=models.CharField(max_length=512, verbose_name="简介"),
        ),
    ]
