# Generated by Django 5.1.3 on 2025-03-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandou", "0004_remove_movie_type_delete_type_movie_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="score",
            field=models.FloatField(blank=True, null=True, verbose_name="评分"),
        ),
    ]
