# Generated by Django 5.1.3 on 2025-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandou", "0008_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating_time",
            field=models.DateTimeField(auto_now=True, verbose_name="评分时间"),
        ),
    ]
