# Generated by Django 5.1.3 on 2025-05-16 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandou", "0010_comments_parent_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
                ),
                (
                    "login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="登录IP"
                    ),
                ),
                (
                    "login_device",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="登录设备"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "登录记录",
                "verbose_name_plural": "登录记录",
                "db_table": "login_record",
                "ordering": ["-login_time"],
            },
        ),
    ]
